import { paymentProxy } from "@x402/next";
import { x402ResourceServer, HTTPFacilitatorClient } from "@x402/core/server";
import { ExactEvmScheme } from "@x402/evm/exact/server";

function getKey(): string {
  const key = process.env.EVM_ADDRESS;
  if (!key) throw new Error("EVM_ADDRESS not set");
  return key;
}

const FACILITATOR_URL = process.env.FACILITATOR_URL || "https://facilitator.payai.network";
const NETWORK = "eip155:8453" as const;

const facilitatorClient = new HTTPFacilitatorClient({ url: FACILITATOR_URL });
const server = new x402ResourceServer(facilitatorClient);
server.register(NETWORK, new ExactEvmScheme());

function p(price: string) {
  return [{ scheme: "exact" as const, price, network: NETWORK, payTo: getKey() }];
}

export const proxy = paymentProxy(
  {
    "POST /api/active-jobs": { accepts: p("$0.080000"), description: "Active Jobs - Other", mimeType: "application/json" },
    "POST /api/active-jobs-db": { accepts: p("$0.050000"), description: "Active Jobs Db - Other", mimeType: "application/json" },
    "POST /api/ai-chat": { accepts: p("$0.130000"), description: "Ai Chat - AI", mimeType: "application/json" },
    "POST /api/ai-content-det6": { accepts: p("$0.120000"), description: "Ai Content Det6 - AI", mimeType: "application/json" },
    "POST /api/ai-content-detector": { accepts: p("$0.120000"), description: "Ai Content Detector - AI", mimeType: "application/json" },
    "POST /api/ai-content-detector-ai-gpt": { accepts: p("$0.090000"), description: "Ai Content Detector Ai Gpt - AI", mimeType: "application/json" },
    "POST /api/ai-doctor": { accepts: p("$0.080000"), description: "Ai Doctor - AI", mimeType: "application/json" },
    "POST /api/ai-image": { accepts: p("$0.070000"), description: "Ai Image - AI", mimeType: "application/json" },
    "POST /api/ai-image-detector": { accepts: p("$0.180000"), description: "Ai Image Detector - AI", mimeType: "application/json" },
    "POST /api/ai-image-gen": { accepts: p("$0.060000"), description: "Ai Image Gen - AI", mimeType: "application/json" },
    "POST /api/ai-overviews": { accepts: p("$0.050000"), description: "Ai Overviews - AI", mimeType: "application/json" },
    "POST /api/ai-text-to-image": { accepts: p("$0.070000"), description: "Ai Text To Image - Tools", mimeType: "application/json" },
    "POST /api/ai-weather": { accepts: p("$0.110000"), description: "Ai Weather - Weather", mimeType: "application/json" },
    "POST /api/airbnb": { accepts: p("$0.120000"), description: "Airbnb - Ecommerce", mimeType: "application/json" },
    "POST /api/airbnb-search": { accepts: p("$0.050000"), description: "Airbnb Search - Ecommerce", mimeType: "application/json" },
    "POST /api/aliexpress-scraper": { accepts: p("$0.110000"), description: "Aliexpress Scraper - Ecommerce", mimeType: "application/json" },
    "POST /api/alpha-vantage": { accepts: p("$0.180000"), description: "Alpha Vantage - Finance", mimeType: "application/json" },
    "POST /api/alpha-vantage-quote": { accepts: p("$0.120000"), description: "Alpha Vantage Quote - Finance", mimeType: "application/json" },
    "POST /api/alt-text": { accepts: p("$0.190000"), description: "Alt Text - Tools", mimeType: "application/json" },
    "POST /api/amazon-axesso": { accepts: p("$0.130000"), description: "Amazon Axesso - Ecommerce", mimeType: "application/json" },
    "POST /api/amazon-data": { accepts: p("$0.050000"), description: "Amazon Data - Ecommerce", mimeType: "application/json" },
    "POST /api/amazon-realtime": { accepts: p("$0.100000"), description: "Amazon Realtime - Ecommerce", mimeType: "application/json" },
    "POST /api/amazon-reviews": { accepts: p("$0.180000"), description: "Amazon Reviews - Ecommerce", mimeType: "application/json" },
    "POST /api/apeguard-solana-token-risk-scanner": { accepts: p("$0.150000"), description: "Apeguard Solana Token Risk Scanner - Crypto", mimeType: "application/json" },
    "POST /api/apiton": { accepts: p("$0.130000"), description: "Apiton - Other", mimeType: "application/json" },
    "POST /api/apjoy-forecast": { accepts: p("$0.090000"), description: "Apjoy Forecast - Weather", mimeType: "application/json" },
    "POST /api/apollo-io": { accepts: p("$0.110000"), description: "Apollo Io - Other", mimeType: "application/json" },
    "POST /api/barcodes1": { accepts: p("$0.150000"), description: "Barcodes1 - Tools", mimeType: "application/json" },
    "POST /api/bg-removal": { accepts: p("$0.080000"), description: "Bg Removal - Tools", mimeType: "application/json" },
    "POST /api/billboard": { accepts: p("$0.070000"), description: "Billboard - Entertainment", mimeType: "application/json" },
    "POST /api/bin-checker": { accepts: p("$0.170000"), description: "Bin Checker - Other", mimeType: "application/json" },
    "POST /api/bin-ip": { accepts: p("$0.080000"), description: "Bin Ip - Other", mimeType: "application/json" },
    "POST /api/bin-ip-checker": { accepts: p("$0.160000"), description: "Bin Ip Checker - Other", mimeType: "application/json" },
    "POST /api/binance": { accepts: p("$0.160000"), description: "Binance - Crypto", mimeType: "application/json" },
    "POST /api/binance-data1": { accepts: p("$0.130000"), description: "Binance Data1 - Crypto", mimeType: "application/json" },
    "POST /api/binance-ticker": { accepts: p("$0.060000"), description: "Binance Ticker - Crypto", mimeType: "application/json" },
    "POST /api/bloomberg-market": { accepts: p("$0.190000"), description: "Bloomberg Market - Finance", mimeType: "application/json" },
    "POST /api/blur": { accepts: p("$0.080000"), description: "Blur - Crypto", mimeType: "application/json" },
    "POST /api/booking-com": { accepts: p("$0.170000"), description: "Booking Com - Ecommerce", mimeType: "application/json" },
    "POST /api/botometer-check": { accepts: p("$0.070000"), description: "Botometer Check - Other", mimeType: "application/json" },
    "POST /api/bypass-cloudflare": { accepts: p("$0.140000"), description: "Bypass Cloudflare - Other", mimeType: "application/json" },
    "POST /api/cellystial": { accepts: p("$0.160000"), description: "Cellystial - Crypto", mimeType: "application/json" },
    "POST /api/chaincheck": { accepts: p("$0.110000"), description: "Chaincheck - Crypto", mimeType: "application/json" },
    "POST /api/chat-gpt26": { accepts: p("$0.070000"), description: "Chat Gpt26 - AI", mimeType: "application/json" },
    "POST /api/chatgpt-42": { accepts: p("$0.060000"), description: "Chatgpt 42 - AI", mimeType: "application/json" },
    "POST /api/chatgpt-4o": { accepts: p("$0.120000"), description: "Chatgpt 4O - AI", mimeType: "application/json" },
    "POST /api/chatgpt-vision": { accepts: p("$0.140000"), description: "Chatgpt Vision - AI", mimeType: "application/json" },
    "POST /api/chatgpt-vision1": { accepts: p("$0.070000"), description: "Chatgpt Vision1 - AI", mimeType: "application/json" },
    "POST /api/chatgpt42": { accepts: p("$0.120000"), description: "Chatgpt42 - AI", mimeType: "application/json" },
    "POST /api/claude": { accepts: p("$0.080000"), description: "Claude - AI", mimeType: "application/json" },
    "POST /api/code-exec": { accepts: p("$0.170000"), description: "Code Exec - Tools", mimeType: "application/json" },
    "POST /api/code-explain": { accepts: p("$0.130000"), description: "Code Explain - Tools", mimeType: "application/json" },
    "POST /api/coinbase": { accepts: p("$0.190000"), description: "Coinbase - Crypto", mimeType: "application/json" },
    "POST /api/coinbase-realtime": { accepts: p("$0.160000"), description: "Coinbase Realtime - Crypto", mimeType: "application/json" },
    "POST /api/coingecko-coins": { accepts: p("$0.100000"), description: "Coingecko Coins - Crypto", mimeType: "application/json" },
    "POST /api/coingecko-price": { accepts: p("$0.160000"), description: "Coingecko Price - Crypto", mimeType: "application/json" },
    "POST /api/coingecko-trending": { accepts: p("$0.160000"), description: "Coingecko Trending - Crypto", mimeType: "application/json" },
    "POST /api/coinmarketcap-listing": { accepts: p("$0.110000"), description: "Coinmarketcap Listing - Crypto", mimeType: "application/json" },
    "POST /api/coinmarketcap-quote": { accepts: p("$0.130000"), description: "Coinmarketcap Quote - Crypto", mimeType: "application/json" },
    "POST /api/coinranking": { accepts: p("$0.070000"), description: "Coinranking - Crypto", mimeType: "application/json" },
    "POST /api/coinranking-coins": { accepts: p("$0.100000"), description: "Coinranking Coins - Crypto", mimeType: "application/json" },
    "POST /api/coinranking1": { accepts: p("$0.120000"), description: "Coinranking1 - Crypto", mimeType: "application/json" },
    "POST /api/contract-events": { accepts: p("$0.100000"), description: "Contract Events - Other", mimeType: "application/json" },
    "POST /api/copilot": { accepts: p("$0.190000"), description: "Copilot - AI", mimeType: "application/json" },
    "POST /api/copilot-chat": { accepts: p("$0.170000"), description: "Copilot Chat - AI", mimeType: "application/json" },
    "POST /api/cricbuzz-cricket": { accepts: p("$0.130000"), description: "Cricbuzz Cricket - Sports", mimeType: "application/json" },
    "POST /api/crypto-exchange": { accepts: p("$0.120000"), description: "Crypto Exchange - Crypto", mimeType: "application/json" },
    "POST /api/crypto-list": { accepts: p("$0.150000"), description: "Crypto List - Crypto", mimeType: "application/json" },
    "POST /api/crypto-market": { accepts: p("$0.060000"), description: "Crypto Market - Crypto", mimeType: "application/json" },
    "POST /api/crypto-news": { accepts: p("$0.120000"), description: "Crypto News - Crypto", mimeType: "application/json" },
    "POST /api/crypto-news16": { accepts: p("$0.060000"), description: "Crypto News16 - Crypto", mimeType: "application/json" },
    "POST /api/crypto-news51": { accepts: p("$0.150000"), description: "Crypto News51 - Crypto", mimeType: "application/json" },
    "POST /api/crypto-news54": { accepts: p("$0.170000"), description: "Crypto News54 - Crypto", mimeType: "application/json" },
    "POST /api/crypto-wallet-address-validator1": { accepts: p("$0.130000"), description: "Crypto Wallet Address Validator1 - Crypto", mimeType: "application/json" },
    "POST /api/crypto/coin": { accepts: p("$0.070000"), description: "Crypto Coin - Crypto", mimeType: "application/json" },
    "POST /api/crypto/coins": { accepts: p("$0.110000"), description: "Crypto Coins - Crypto", mimeType: "application/json" },
    "POST /api/cryptography": { accepts: p("$0.150000"), description: "Cryptography - Crypto", mimeType: "application/json" },
    "POST /api/csv-parse": { accepts: p("$0.110000"), description: "Csv Parse - Tools", mimeType: "application/json" },
    "POST /api/datanest-forecast": { accepts: p("$0.200000"), description: "Datanest Forecast - Weather", mimeType: "application/json" },
    "POST /api/datanest-weather": { accepts: p("$0.170000"), description: "Datanest Weather - Weather", mimeType: "application/json" },
    "POST /api/defi-liquidation-alert": { accepts: p("$0.190000"), description: "Defi Liquidation Alert - Crypto", mimeType: "application/json" },
    "POST /api/defi-yield": { accepts: p("$0.090000"), description: "Defi Yield - Crypto", mimeType: "application/json" },
    "POST /api/defillama-protocols": { accepts: p("$0.130000"), description: "Defillama Protocols - Crypto", mimeType: "application/json" },
    "POST /api/defillama-tvl": { accepts: p("$0.090000"), description: "Defillama Tvl - Crypto", mimeType: "application/json" },
    "POST /api/defillama-yields": { accepts: p("$0.120000"), description: "Defillama Yields - Crypto", mimeType: "application/json" },
    "POST /api/dev-intelligence": { accepts: p("$0.130000"), description: "Dev Intelligence - Other", mimeType: "application/json" },
    "POST /api/discord-shield": { accepts: p("$0.180000"), description: "Discord Shield - Social Media", mimeType: "application/json" },
    "POST /api/domain-check": { accepts: p("$0.170000"), description: "Domain Check - Tools", mimeType: "application/json" },
    "POST /api/domain-checker": { accepts: p("$0.160000"), description: "Domain Checker - Tools", mimeType: "application/json" },
    "POST /api/domain-da-pa-check": { accepts: p("$0.120000"), description: "Domain Da Pa Check - Tools", mimeType: "application/json" },
    "POST /api/domain-da-pa-checker": { accepts: p("$0.090000"), description: "Domain Da Pa Checker - Tools", mimeType: "application/json" },
    "POST /api/douyin-api": { accepts: p("$0.200000"), description: "Douyin Api - Social Media", mimeType: "application/json" },
    "POST /api/easy-weather": { accepts: p("$0.070000"), description: "Easy Weather - Weather", mimeType: "application/json" },
    "POST /api/edge-tts": { accepts: p("$0.060000"), description: "Edge Tts - Tools", mimeType: "application/json" },
    "POST /api/emails-extractor": { accepts: p("$0.080000"), description: "Emails Extractor - Tools", mimeType: "application/json" },
    "POST /api/emails-social-extractor": { accepts: p("$0.090000"), description: "Emails Social Extractor - Tools", mimeType: "application/json" },
    "POST /api/exchange-rates": { accepts: p("$0.100000"), description: "Exchange Rates - Finance", mimeType: "application/json" },
    "POST /api/exchange/convert": { accepts: p("$0.180000"), description: "Exchange Convert - Finance", mimeType: "application/json" },
    "POST /api/exchange/rates": { accepts: p("$0.070000"), description: "Exchange Rates - Finance", mimeType: "application/json" },
    "POST /api/exchangerate-convert": { accepts: p("$0.170000"), description: "Exchangerate Convert - Finance", mimeType: "application/json" },
    "POST /api/extract-keywords": { accepts: p("$0.170000"), description: "Extract Keywords - Other", mimeType: "application/json" },
    "POST /api/face-analyzer": { accepts: p("$0.190000"), description: "Face Analyzer - Other", mimeType: "application/json" },
    "POST /api/facebook-pages-scraper": { accepts: p("$0.130000"), description: "Facebook Pages Scraper - Social Media", mimeType: "application/json" },
    "POST /api/facebook-pages-scraper2": { accepts: p("$0.050000"), description: "Facebook Pages Scraper2 - Social Media", mimeType: "application/json" },
    "POST /api/facebook-scraper": { accepts: p("$0.080000"), description: "Facebook Scraper - Social Media", mimeType: "application/json" },
    "POST /api/facebook-scraper-api4": { accepts: p("$0.130000"), description: "Facebook Scraper Api4 - Social Media", mimeType: "application/json" },
    "POST /api/find-fb-ig": { accepts: p("$0.150000"), description: "Find Fb Ig - Other", mimeType: "application/json" },
    "POST /api/flashapi-scraper": { accepts: p("$0.080000"), description: "Flashapi Scraper - Tools", mimeType: "application/json" },
    "POST /api/flashapi1": { accepts: p("$0.140000"), description: "Flashapi1 - Tools", mimeType: "application/json" },
    "POST /api/football-prediction": { accepts: p("$0.180000"), description: "Football Prediction - Sports", mimeType: "application/json" },
    "POST /api/foreca": { accepts: p("$0.100000"), description: "Foreca - Weather", mimeType: "application/json" },
    "POST /api/forex-factory": { accepts: p("$0.190000"), description: "Forex Factory - Finance", mimeType: "application/json" },
    "POST /api/free-chatgpt": { accepts: p("$0.050000"), description: "Free Chatgpt - AI", mimeType: "application/json" },
    "POST /api/fuel-price": { accepts: p("$0.130000"), description: "Fuel Price - Other", mimeType: "application/json" },
    "POST /api/gas-estimate": { accepts: p("$0.100000"), description: "Gas Estimate - Other", mimeType: "application/json" },
    "POST /api/gemini": { accepts: p("$0.080000"), description: "Gemini - AI", mimeType: "application/json" },
    "POST /api/ghibli-gen": { accepts: p("$0.140000"), description: "Ghibli Gen - AI", mimeType: "application/json" },
    "POST /api/gmailnator": { accepts: p("$0.110000"), description: "Gmailnator - Tools", mimeType: "application/json" },
    "POST /api/gold-silver": { accepts: p("$0.090000"), description: "Gold Silver - Finance", mimeType: "application/json" },
    "POST /api/gold-silver-india": { accepts: p("$0.160000"), description: "Gold Silver India - Finance", mimeType: "application/json" },
    "POST /api/google-ad-library": { accepts: p("$0.100000"), description: "Google Ad Library - Tools", mimeType: "application/json" },
    "POST /api/google-ai-overviews": { accepts: p("$0.050000"), description: "Google Ai Overviews - AI", mimeType: "application/json" },
    "POST /api/google-news": { accepts: p("$0.150000"), description: "Google News - News", mimeType: "application/json" },
    "POST /api/google-serp": { accepts: p("$0.200000"), description: "Google Serp - Tools", mimeType: "application/json" },
    "POST /api/gov/proposals": { accepts: p("$0.050000"), description: "Gov Proposals - Other", mimeType: "application/json" },
    "POST /api/gov/treasury": { accepts: p("$0.080000"), description: "Gov Treasury - Other", mimeType: "application/json" },
    "POST /api/gov/vote-results": { accepts: p("$0.160000"), description: "Gov Vote Results - Other", mimeType: "application/json" },
    "POST /api/gov/whale-votes": { accepts: p("$0.140000"), description: "Gov Whale Votes - Other", mimeType: "application/json" },
    "POST /api/governance": { accepts: p("$0.120000"), description: "Governance - Other", mimeType: "application/json" },
    "POST /api/gpt5": { accepts: p("$0.060000"), description: "Gpt5 - AI", mimeType: "application/json" },
    "POST /api/hash-generate": { accepts: p("$0.120000"), description: "Hash Generate - Tools", mimeType: "application/json" },
    "POST /api/humanize-ai": { accepts: p("$0.070000"), description: "Humanize Ai - AI", mimeType: "application/json" },
    "POST /api/hyperliquid": { accepts: p("$0.070000"), description: "Hyperliquid - Crypto", mimeType: "application/json" },
    "POST /api/hyperliquid-meta": { accepts: p("$0.200000"), description: "Hyperliquid Meta - Crypto", mimeType: "application/json" },
    "POST /api/hyperliquid-orderbook": { accepts: p("$0.070000"), description: "Hyperliquid Orderbook - Crypto", mimeType: "application/json" },
    "POST /api/ig-ai": { accepts: p("$0.090000"), description: "Ig Ai - Social Media", mimeType: "application/json" },
    "POST /api/ig-api-fast": { accepts: p("$0.090000"), description: "Ig Api Fast - Social Media", mimeType: "application/json" },
    "POST /api/ig-best": { accepts: p("$0.200000"), description: "Ig Best - Social Media", mimeType: "application/json" },
    "POST /api/ig-bulk": { accepts: p("$0.100000"), description: "Ig Bulk - Social Media", mimeType: "application/json" },
    "POST /api/ig-cheap": { accepts: p("$0.130000"), description: "Ig Cheap - Social Media", mimeType: "application/json" },
    "POST /api/ig-checker": { accepts: p("$0.180000"), description: "Ig Checker - Social Media", mimeType: "application/json" },
    "POST /api/ig-dl-reels": { accepts: p("$0.110000"), description: "Ig Dl Reels - Social Media", mimeType: "application/json" },
    "POST /api/ig-media": { accepts: p("$0.110000"), description: "Ig Media - Social Media", mimeType: "application/json" },
    "POST /api/ig-post-dl": { accepts: p("$0.140000"), description: "Ig Post Dl - Social Media", mimeType: "application/json" },
    "POST /api/ig-scraper-stories": { accepts: p("$0.170000"), description: "Ig Scraper Stories - Social Media", mimeType: "application/json" },
    "POST /api/ig-simple": { accepts: p("$0.160000"), description: "Ig Simple - Social Media", mimeType: "application/json" },
    "POST /api/ig-social": { accepts: p("$0.190000"), description: "Ig Social - Social Media", mimeType: "application/json" },
    "POST /api/ig-stable": { accepts: p("$0.190000"), description: "Ig Stable - Social Media", mimeType: "application/json" },
    "POST /api/ig-stats": { accepts: p("$0.080000"), description: "Ig Stats - Social Media", mimeType: "application/json" },
    "POST /api/ig-story-dl": { accepts: p("$0.120000"), description: "Ig Story Dl - Social Media", mimeType: "application/json" },
    "POST /api/ig191": { accepts: p("$0.120000"), description: "Ig191 - Other", mimeType: "application/json" },
    "POST /api/ig360": { accepts: p("$0.070000"), description: "Ig360 - Other", mimeType: "application/json" },
    "POST /api/ig39": { accepts: p("$0.150000"), description: "Ig39 - Other", mimeType: "application/json" },
    "POST /api/ikea-api-pro": { accepts: p("$0.050000"), description: "Ikea Api Pro - Ecommerce", mimeType: "application/json" },
    "POST /api/ikea-products": { accepts: p("$0.120000"), description: "Ikea Products - Ecommerce", mimeType: "application/json" },
    "POST /api/india-stock": { accepts: p("$0.120000"), description: "India Stock - Finance", mimeType: "application/json" },
    "POST /api/indian-exchange": { accepts: p("$0.050000"), description: "Indian Exchange - Finance", mimeType: "application/json" },
    "POST /api/indian-ipo": { accepts: p("$0.070000"), description: "Indian Ipo - Finance", mimeType: "application/json" },
    "POST /api/indian-market-data": { accepts: p("$0.060000"), description: "Indian Market Data - Finance", mimeType: "application/json" },
    "POST /api/indian-sentiment": { accepts: p("$0.120000"), description: "Indian Sentiment - Finance", mimeType: "application/json" },
    "POST /api/indian-stock-exchange": { accepts: p("$0.070000"), description: "Indian Stock Exchange - Finance", mimeType: "application/json" },
    "POST /api/indian-stock-exchange-api2": { accepts: p("$0.060000"), description: "Indian Stock Exchange Api2 - Finance", mimeType: "application/json" },
    "POST /api/indian-stock-fundamentals": { accepts: p("$0.150000"), description: "Indian Stock Fundamentals - Finance", mimeType: "application/json" },
    "POST /api/indian-stock-market-data-nse-bse-bcd-mcx-cds-nfo": { accepts: p("$0.070000"), description: "Indian Stock Market Data Nse Bse Bcd Mcx Cds Nfo - Finance", mimeType: "application/json" },
    "POST /api/indian-stock-moneycontrol": { accepts: p("$0.120000"), description: "Indian Stock Moneycontrol - Finance", mimeType: "application/json" },
    "POST /api/insider-trades": { accepts: p("$0.130000"), description: "Insider Trades - Finance", mimeType: "application/json" },
    "POST /api/insightsentry": { accepts: p("$0.200000"), description: "Insightsentry - Other", mimeType: "application/json" },
    "POST /api/instagram-api-fast-reliable-data-scraper": { accepts: p("$0.110000"), description: "Instagram Api Fast Reliable Data Scraper - Social Media", mimeType: "application/json" },
    "POST /api/instagram-api68": { accepts: p("$0.090000"), description: "Instagram Api68 - Social Media", mimeType: "application/json" },
    "POST /api/instagram-downloader": { accepts: p("$0.200000"), description: "Instagram Downloader - Social Media", mimeType: "application/json" },
    "POST /api/instagram-downloader-scraper-reels-igtv-posts-stories": { accepts: p("$0.120000"), description: "Instagram Downloader Scraper Reels Igtv Posts Stories - Social Media", mimeType: "application/json" },
    "POST /api/instagram-downloader-v2-scraper-reels-igtv-posts-stories": { accepts: p("$0.200000"), description: "Instagram Downloader V2 Scraper Reels Igtv Posts Stories - Social Media", mimeType: "application/json" },
    "POST /api/instagram-looter": { accepts: p("$0.180000"), description: "Instagram Looter - Social Media", mimeType: "application/json" },
    "POST /api/instagram-looter2": { accepts: p("$0.110000"), description: "Instagram Looter2 - Social Media", mimeType: "application/json" },
    "POST /api/instagram-scraper": { accepts: p("$0.080000"), description: "Instagram Scraper - Social Media", mimeType: "application/json" },
    "POST /api/instagram-scraper-20251": { accepts: p("$0.080000"), description: "Instagram Scraper 20251 - Social Media", mimeType: "application/json" },
    "POST /api/instagram-scraper-stable-api": { accepts: p("$0.180000"), description: "Instagram Scraper Stable Api - Social Media", mimeType: "application/json" },
    "POST /api/instagram-stable-scraper": { accepts: p("$0.160000"), description: "Instagram Stable Scraper - Social Media", mimeType: "application/json" },
    "POST /api/instagram-statistics": { accepts: p("$0.180000"), description: "Instagram Statistics - Social Media", mimeType: "application/json" },
    "POST /api/instagram120": { accepts: p("$0.180000"), description: "Instagram120 - Social Media", mimeType: "application/json" },
    "POST /api/instagram360": { accepts: p("$0.190000"), description: "Instagram360 - Social Media", mimeType: "application/json" },
    "POST /api/irctc": { accepts: p("$0.060000"), description: "Irctc - India", mimeType: "application/json" },
    "POST /api/job-posting-feed-api": { accepts: p("$0.080000"), description: "Job Posting Feed Api - Other", mimeType: "application/json" },
    "POST /api/jsearch-jobs": { accepts: p("$0.060000"), description: "Jsearch Jobs - Other", mimeType: "application/json" },
    "POST /api/json-repair": { accepts: p("$0.170000"), description: "Json Repair - Tools", mimeType: "application/json" },
    "POST /api/json-transform": { accepts: p("$0.150000"), description: "Json Transform - Tools", mimeType: "application/json" },
    "POST /api/li-data-scraper": { accepts: p("$0.080000"), description: "Li Data Scraper - Social Media", mimeType: "application/json" },
    "POST /api/linkedin-b2b-data-enrichment-apis-blitzapi": { accepts: p("$0.120000"), description: "Linkedin B2B Data Enrichment Apis Blitzapi - Social Media", mimeType: "application/json" },
    "POST /api/linkedin-bulk-data-scraper": { accepts: p("$0.110000"), description: "Linkedin Bulk Data Scraper - Social Media", mimeType: "application/json" },
    "POST /api/linkedin-bulk-scraper": { accepts: p("$0.110000"), description: "Linkedin Bulk Scraper - Social Media", mimeType: "application/json" },
    "POST /api/linkedin-data": { accepts: p("$0.190000"), description: "Linkedin Data - Social Media", mimeType: "application/json" },
    "POST /api/linkedin-data-scraper": { accepts: p("$0.090000"), description: "Linkedin Data Scraper - Social Media", mimeType: "application/json" },
    "POST /api/linkedin-data-scraper-alt": { accepts: p("$0.180000"), description: "Linkedin Data Scraper Alt - Social Media", mimeType: "application/json" },
    "POST /api/linkedin-profile": { accepts: p("$0.100000"), description: "Linkedin Profile - Social Media", mimeType: "application/json" },
    "POST /api/linkedin-sales-navigator": { accepts: p("$0.130000"), description: "Linkedin Sales Navigator - Social Media", mimeType: "application/json" },
    "POST /api/linkedin-scraper": { accepts: p("$0.190000"), description: "Linkedin Scraper - Social Media", mimeType: "application/json" },
    "POST /api/live-metal-prices": { accepts: p("$0.120000"), description: "Live Metal Prices - Finance", mimeType: "application/json" },
    "POST /api/live-stock": { accepts: p("$0.070000"), description: "Live Stock - Finance", mimeType: "application/json" },
    "POST /api/local-business": { accepts: p("$0.190000"), description: "Local Business - Other", mimeType: "application/json" },
    "POST /api/local-business-data": { accepts: p("$0.080000"), description: "Local Business Data - Other", mimeType: "application/json" },
    "POST /api/lodestar-price": { accepts: p("$0.060000"), description: "Lodestar Price - Crypto", mimeType: "application/json" },
    "POST /api/maps-data": { accepts: p("$0.050000"), description: "Maps Data - Other", mimeType: "application/json" },
    "POST /api/medium-articles": { accepts: p("$0.070000"), description: "Medium Articles - Social Media", mimeType: "application/json" },
    "POST /api/medium2": { accepts: p("$0.120000"), description: "Medium2 - Social Media", mimeType: "application/json" },
    "POST /api/metat": { accepts: p("$0.100000"), description: "Metat - Other", mimeType: "application/json" },
    "POST /api/meteostat": { accepts: p("$0.180000"), description: "Meteostat - Weather", mimeType: "application/json" },
    "POST /api/moneycontrol-live": { accepts: p("$0.200000"), description: "Moneycontrol Live - Finance", mimeType: "application/json" },
    "POST /api/nse-stock": { accepts: p("$0.200000"), description: "Nse Stock - Finance", mimeType: "application/json" },
    "POST /api/open-ai21": { accepts: p("$0.110000"), description: "Open Ai21 - AI", mimeType: "application/json" },
    "POST /api/open-weather": { accepts: p("$0.170000"), description: "Open Weather - Weather", mimeType: "application/json" },
    "POST /api/open-weather-map": { accepts: p("$0.060000"), description: "Open Weather Map - Weather", mimeType: "application/json" },
    "POST /api/open-weather13": { accepts: p("$0.100000"), description: "Open Weather13 - Weather", mimeType: "application/json" },
    "POST /api/opensea15": { accepts: p("$0.170000"), description: "Opensea15 - Crypto", mimeType: "application/json" },
    "POST /api/password-gen": { accepts: p("$0.050000"), description: "Password Gen - Tools", mimeType: "application/json" },
    "POST /api/pickleball": { accepts: p("$0.170000"), description: "Pickleball - Sports", mimeType: "application/json" },
    "POST /api/pokemon-auth": { accepts: p("$0.130000"), description: "Pokemon Auth - Entertainment", mimeType: "application/json" },
    "POST /api/polymarket-events": { accepts: p("$0.190000"), description: "Polymarket Events - Crypto", mimeType: "application/json" },
    "POST /api/polymarket-markets": { accepts: p("$0.140000"), description: "Polymarket Markets - Crypto", mimeType: "application/json" },
    "POST /api/pretrade": { accepts: p("$0.180000"), description: "Pretrade - Other", mimeType: "application/json" },
    "POST /api/raydium-memecoin-radar-solana-live-detection": { accepts: p("$0.200000"), description: "Raydium Memecoin Radar Solana Live Detection - Crypto", mimeType: "application/json" },
    "POST /api/real-time-amazon-data": { accepts: p("$0.090000"), description: "Real Time Amazon Data - Ecommerce", mimeType: "application/json" },
    "POST /api/real-time-image-search": { accepts: p("$0.110000"), description: "Real Time Image Search - Tools", mimeType: "application/json" },
    "POST /api/real-time-news": { accepts: p("$0.140000"), description: "Real Time News - News", mimeType: "application/json" },
    "POST /api/real-time-news-data": { accepts: p("$0.110000"), description: "Real Time News Data - News", mimeType: "application/json" },
    "POST /api/realtime-finance": { accepts: p("$0.060000"), description: "Realtime Finance - Finance", mimeType: "application/json" },
    "POST /api/runwayml-generate": { accepts: p("$0.060000"), description: "Runwayml Generate - AI", mimeType: "application/json" },
    "POST /api/safevision": { accepts: p("$0.150000"), description: "Safevision - Other", mimeType: "application/json" },
    "POST /api/scrapeninja": { accepts: p("$0.060000"), description: "Scrapeninja - Tools", mimeType: "application/json" },
    "POST /api/scraptik": { accepts: p("$0.060000"), description: "Scraptik - Social Media", mimeType: "application/json" },
    "POST /api/screener": { accepts: p("$0.200000"), description: "Screener - Finance", mimeType: "application/json" },
    "POST /api/screener-official": { accepts: p("$0.100000"), description: "Screener Official - Finance", mimeType: "application/json" },
    "POST /api/screenshot-twitter": { accepts: p("$0.060000"), description: "Screenshot Twitter - Social Media", mimeType: "application/json" },
    "POST /api/sea-temperature": { accepts: p("$0.070000"), description: "Sea Temperature - Weather", mimeType: "application/json" },
    "POST /api/sec-risk": { accepts: p("$0.100000"), description: "Sec Risk - Finance", mimeType: "application/json" },
    "POST /api/seeking-alpha": { accepts: p("$0.070000"), description: "Seeking Alpha - Finance", mimeType: "application/json" },
    "POST /api/seeking-alpha-finance": { accepts: p("$0.070000"), description: "Seeking Alpha Finance - Finance", mimeType: "application/json" },
    "POST /api/sentiment/fear-greed": { accepts: p("$0.120000"), description: "Sentiment Fear Greed - Other", mimeType: "application/json" },
    "POST /api/sentiment/news": { accepts: p("$0.170000"), description: "Sentiment News - News", mimeType: "application/json" },
    "POST /api/sentiment/token": { accepts: p("$0.080000"), description: "Sentiment Token - Crypto", mimeType: "application/json" },
    "POST /api/sentiment/trending": { accepts: p("$0.120000"), description: "Sentiment Trending - Other", mimeType: "application/json" },
    "POST /api/seo-audit": { accepts: p("$0.060000"), description: "Seo Audit - Tools", mimeType: "application/json" },
    "POST /api/share-market-news": { accepts: p("$0.070000"), description: "Share Market News - Finance", mimeType: "application/json" },
    "POST /api/shopee-all-in-one": { accepts: p("$0.180000"), description: "Shopee All In One - Ecommerce", mimeType: "application/json" },
    "POST /api/shopee-product": { accepts: p("$0.150000"), description: "Shopee Product - Ecommerce", mimeType: "application/json" },
    "POST /api/shopee-scraper": { accepts: p("$0.130000"), description: "Shopee Scraper - Ecommerce", mimeType: "application/json" },
    "POST /api/similar-web-api": { accepts: p("$0.110000"), description: "Similar Web Api - Tools", mimeType: "application/json" },
    "POST /api/similarweb": { accepts: p("$0.150000"), description: "Similarweb - Other", mimeType: "application/json" },
    "POST /api/ski-resort": { accepts: p("$0.120000"), description: "Ski Resort - Weather", mimeType: "application/json" },
    "POST /api/skip-tracing": { accepts: p("$0.130000"), description: "Skip Tracing - Tools", mimeType: "application/json" },
    "POST /api/sky-scrapper": { accepts: p("$0.170000"), description: "Sky Scrapper - Travel", mimeType: "application/json" },
    "POST /api/smart-scraper": { accepts: p("$0.090000"), description: "Smart Scraper - Tools", mimeType: "application/json" },
    "POST /api/snap-video": { accepts: p("$0.140000"), description: "Snap Video - Other", mimeType: "application/json" },
    "POST /api/social-analytics": { accepts: p("$0.190000"), description: "Social Analytics - Other", mimeType: "application/json" },
    "POST /api/social-scanner": { accepts: p("$0.150000"), description: "Social Scanner - Other", mimeType: "application/json" },
    "POST /api/social-video-dl": { accepts: p("$0.070000"), description: "Social Video Dl - Other", mimeType: "application/json" },
    "POST /api/social-video-dl2": { accepts: p("$0.050000"), description: "Social Video Dl2 - Other", mimeType: "application/json" },
    "POST /api/solana-wallet-portfolio-balance-api": { accepts: p("$0.190000"), description: "Solana Wallet Portfolio Balance Api - Crypto", mimeType: "application/json" },
    "POST /api/sonoteller": { accepts: p("$0.080000"), description: "Sonoteller - Entertainment", mimeType: "application/json" },
    "POST /api/speech-to-text": { accepts: p("$0.070000"), description: "Speech To Text - Tools", mimeType: "application/json" },
    "POST /api/sportapi7": { accepts: p("$0.110000"), description: "Sportapi7 - Sports", mimeType: "application/json" },
    "POST /api/spotify-data": { accepts: p("$0.130000"), description: "Spotify Data - Social Media", mimeType: "application/json" },
    "POST /api/steam-business": { accepts: p("$0.090000"), description: "Steam Business - Gaming", mimeType: "application/json" },
    "POST /api/taobao-1688": { accepts: p("$0.160000"), description: "Taobao 1688 - Ecommerce", mimeType: "application/json" },
    "POST /api/taobao-scraper": { accepts: p("$0.070000"), description: "Taobao Scraper - Ecommerce", mimeType: "application/json" },
    "POST /api/telegram-channel": { accepts: p("$0.120000"), description: "Telegram Channel - Social Media", mimeType: "application/json" },
    "POST /api/telegram-index": { accepts: p("$0.160000"), description: "Telegram Index - Social Media", mimeType: "application/json" },
    "POST /api/temp-gmail": { accepts: p("$0.140000"), description: "Temp Gmail - Tools", mimeType: "application/json" },
    "POST /api/tensor": { accepts: p("$0.100000"), description: "Tensor - Crypto", mimeType: "application/json" },
    "POST /api/text-stats": { accepts: p("$0.190000"), description: "Text Stats - Tools", mimeType: "application/json" },
    "POST /api/therundown-therundown-v1": { accepts: p("$0.140000"), description: "Therundown Therundown V1 - Sports", mimeType: "application/json" },
    "POST /api/threads-api": { accepts: p("$0.050000"), description: "Threads Api - Social Media", mimeType: "application/json" },
    "POST /api/tidecheck": { accepts: p("$0.140000"), description: "Tidecheck - Weather", mimeType: "application/json" },
    "POST /api/tiktok-api-fast-reliable-data-scraper": { accepts: p("$0.080000"), description: "Tiktok Api Fast Reliable Data Scraper - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-api15": { accepts: p("$0.090000"), description: "Tiktok Api15 - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-api23": { accepts: p("$0.130000"), description: "Tiktok Api23 - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-api6": { accepts: p("$0.080000"), description: "Tiktok Api6 - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-best": { accepts: p("$0.080000"), description: "Tiktok Best - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-creative": { accepts: p("$0.090000"), description: "Tiktok Creative - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-dl-api": { accepts: p("$0.130000"), description: "Tiktok Dl Api - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-download": { accepts: p("$0.140000"), description: "Tiktok Download - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-fast": { accepts: p("$0.110000"), description: "Tiktok Fast - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-feed": { accepts: p("$0.150000"), description: "Tiktok Feed - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-full": { accepts: p("$0.110000"), description: "Tiktok Full - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-hd": { accepts: p("$0.130000"), description: "Tiktok Hd - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-nowm": { accepts: p("$0.200000"), description: "Tiktok Nowm - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-nowm10": { accepts: p("$0.130000"), description: "Tiktok Nowm10 - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-private": { accepts: p("$0.060000"), description: "Tiktok Private - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-scraper": { accepts: p("$0.070000"), description: "Tiktok Scraper - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-scraper7": { accepts: p("$0.180000"), description: "Tiktok Scraper7 - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-scrapper": { accepts: p("$0.130000"), description: "Tiktok Scrapper - Social Media", mimeType: "application/json" },
    "POST /api/tiktok-shop": { accepts: p("$0.060000"), description: "Tiktok Shop - Social Media", mimeType: "application/json" },
    "POST /api/tiktok82": { accepts: p("$0.050000"), description: "Tiktok82 - Social Media", mimeType: "application/json" },
    "POST /api/today-football-prediction": { accepts: p("$0.150000"), description: "Today Football Prediction - Sports", mimeType: "application/json" },
    "POST /api/tokapi-mobile": { accepts: p("$0.090000"), description: "Tokapi Mobile - Social Media", mimeType: "application/json" },
    "POST /api/ton-fragment": { accepts: p("$0.130000"), description: "Ton Fragment - Other", mimeType: "application/json" },
    "POST /api/trading-economics": { accepts: p("$0.100000"), description: "Trading Economics - Finance", mimeType: "application/json" },
    "POST /api/trading-signals": { accepts: p("$0.190000"), description: "Trading Signals - Finance", mimeType: "application/json" },
    "POST /api/tradingview-screener": { accepts: p("$0.180000"), description: "Tradingview Screener - Finance", mimeType: "application/json" },
    "POST /api/tradingview-technical": { accepts: p("$0.050000"), description: "Tradingview Technical - Finance", mimeType: "application/json" },
    "POST /api/translate-all": { accepts: p("$0.080000"), description: "Translate All - Tools", mimeType: "application/json" },
    "POST /api/tripadvisor": { accepts: p("$0.070000"), description: "Tripadvisor - Travel", mimeType: "application/json" },
    "POST /api/truecaller-lookup": { accepts: p("$0.090000"), description: "Truecaller Lookup - Tools", mimeType: "application/json" },
    "POST /api/twelve-data-quote": { accepts: p("$0.060000"), description: "Twelve Data Quote - Finance", mimeType: "application/json" },
    "POST /api/twitch-scraper": { accepts: p("$0.160000"), description: "Twitch Scraper - Social Media", mimeType: "application/json" },
    "POST /api/twitter-aio": { accepts: p("$0.090000"), description: "Twitter Aio - Social Media", mimeType: "application/json" },
    "POST /api/twitter-aio-search": { accepts: p("$0.180000"), description: "Twitter Aio Search - Social Media", mimeType: "application/json" },
    "POST /api/twitter-api45": { accepts: p("$0.090000"), description: "Twitter Api45 - Social Media", mimeType: "application/json" },
    "POST /api/twitter-api45-user": { accepts: p("$0.060000"), description: "Twitter Api45 User - Social Media", mimeType: "application/json" },
    "POST /api/twitter-api47": { accepts: p("$0.140000"), description: "Twitter Api47 - Social Media", mimeType: "application/json" },
    "POST /api/twitter-api47-user": { accepts: p("$0.160000"), description: "Twitter Api47 User - Social Media", mimeType: "application/json" },
    "POST /api/twitter-cheap": { accepts: p("$0.060000"), description: "Twitter Cheap - Social Media", mimeType: "application/json" },
    "POST /api/twitter-data-user": { accepts: p("$0.160000"), description: "Twitter Data User - Social Media", mimeType: "application/json" },
    "POST /api/twitter-enterprise": { accepts: p("$0.110000"), description: "Twitter Enterprise - Social Media", mimeType: "application/json" },
    "POST /api/twitter-fast": { accepts: p("$0.120000"), description: "Twitter Fast - Social Media", mimeType: "application/json" },
    "POST /api/twitter-followers": { accepts: p("$0.080000"), description: "Twitter Followers - Social Media", mimeType: "application/json" },
    "POST /api/twitter-search-only": { accepts: p("$0.160000"), description: "Twitter Search Only - Social Media", mimeType: "application/json" },
    "POST /api/twitter-social": { accepts: p("$0.180000"), description: "Twitter Social - Social Media", mimeType: "application/json" },
    "POST /api/twitter-spaces": { accepts: p("$0.090000"), description: "Twitter Spaces - Social Media", mimeType: "application/json" },
    "POST /api/twitter-trending": { accepts: p("$0.120000"), description: "Twitter Trending - Social Media", mimeType: "application/json" },
    "POST /api/twitter-user-followers": { accepts: p("$0.100000"), description: "Twitter User Followers - Social Media", mimeType: "application/json" },
    "POST /api/twitter-user-info": { accepts: p("$0.100000"), description: "Twitter User Info - Social Media", mimeType: "application/json" },
    "POST /api/twitter-user-tweets": { accepts: p("$0.180000"), description: "Twitter User Tweets - Social Media", mimeType: "application/json" },
    "POST /api/twitter-v1-1-v2-api": { accepts: p("$0.050000"), description: "Twitter V1 1 V2 Api - Social Media", mimeType: "application/json" },
    "POST /api/twitter-v1-timeline": { accepts: p("$0.100000"), description: "Twitter V1 Timeline - Social Media", mimeType: "application/json" },
    "POST /api/twitter-v1v2": { accepts: p("$0.150000"), description: "Twitter V1V2 - Social Media", mimeType: "application/json" },
    "POST /api/twitter-v2-search": { accepts: p("$0.180000"), description: "Twitter V2 Search - Social Media", mimeType: "application/json" },
    "POST /api/twitter-v24": { accepts: p("$0.120000"), description: "Twitter V24 - Social Media", mimeType: "application/json" },
    "POST /api/twitter-video-dl": { accepts: p("$0.130000"), description: "Twitter Video Dl - Social Media", mimeType: "application/json" },
    "POST /api/twitter-x": { accepts: p("$0.100000"), description: "Twitter X - Social Media", mimeType: "application/json" },
    "POST /api/twitter-x-api": { accepts: p("$0.080000"), description: "Twitter X Api - Social Media", mimeType: "application/json" },
    "POST /api/twitter-x-profile": { accepts: p("$0.170000"), description: "Twitter X Profile - Social Media", mimeType: "application/json" },
    "POST /api/twitter-x-video-dl": { accepts: p("$0.060000"), description: "Twitter X Video Dl - Social Media", mimeType: "application/json" },
    "POST /api/twitter135": { accepts: p("$0.200000"), description: "Twitter135 - Social Media", mimeType: "application/json" },
    "POST /api/twitter135-search": { accepts: p("$0.120000"), description: "Twitter135 Search - Social Media", mimeType: "application/json" },
    "POST /api/twitter154": { accepts: p("$0.110000"), description: "Twitter154 - Social Media", mimeType: "application/json" },
    "POST /api/twitter154-search": { accepts: p("$0.190000"), description: "Twitter154 Search - Social Media", mimeType: "application/json" },
    "POST /api/twitter293": { accepts: p("$0.160000"), description: "Twitter293 - Social Media", mimeType: "application/json" },
    "POST /api/twitter293-user": { accepts: p("$0.140000"), description: "Twitter293 User - Social Media", mimeType: "application/json" },
    "POST /api/twitter303": { accepts: p("$0.120000"), description: "Twitter303 - Social Media", mimeType: "application/json" },
    "POST /api/twitter32": { accepts: p("$0.120000"), description: "Twitter32 - Social Media", mimeType: "application/json" },
    "POST /api/ultimate-economic-calendar": { accepts: p("$0.050000"), description: "Ultimate Economic Calendar - Finance", mimeType: "application/json" },
    "POST /api/url-to-text": { accepts: p("$0.110000"), description: "Url To Text - Tools", mimeType: "application/json" },
    "POST /api/username-check": { accepts: p("$0.170000"), description: "Username Check - Tools", mimeType: "application/json" },
    "POST /api/video-transcript": { accepts: p("$0.150000"), description: "Video Transcript - Tools", mimeType: "application/json" },
    "POST /api/video-transcript-scraper": { accepts: p("$0.130000"), description: "Video Transcript Scraper - Tools", mimeType: "application/json" },
    "POST /api/visual-crossing": { accepts: p("$0.070000"), description: "Visual Crossing - Weather", mimeType: "application/json" },
    "POST /api/wallet-validator": { accepts: p("$0.130000"), description: "Wallet Validator - Crypto", mimeType: "application/json" },
    "POST /api/weather-api": { accepts: p("$0.160000"), description: "Weather Api - Weather", mimeType: "application/json" },
    "POST /api/weather-db": { accepts: p("$0.170000"), description: "Weather Db - Weather", mimeType: "application/json" },
    "POST /api/weather138": { accepts: p("$0.150000"), description: "Weather138 - Weather", mimeType: "application/json" },
    "POST /api/weather338": { accepts: p("$0.050000"), description: "Weather338 - Weather", mimeType: "application/json" },
    "POST /api/weatherapi": { accepts: p("$0.080000"), description: "Weatherapi - Weather", mimeType: "application/json" },
    "POST /api/weatherapi-com": { accepts: p("$0.130000"), description: "Weatherapi Com - Weather", mimeType: "application/json" },
    "POST /api/weatherbit-v1-mashape": { accepts: p("$0.100000"), description: "Weatherbit V1 Mashape - Weather", mimeType: "application/json" },
    "POST /api/web-scraping-api": { accepts: p("$0.130000"), description: "Web Scraping Api - Tools", mimeType: "application/json" },
    "POST /api/web-search": { accepts: p("$0.060000"), description: "Web Search - Tools", mimeType: "application/json" },
    "POST /api/website-contactcrawler": { accepts: p("$0.080000"), description: "Website Contactcrawler - Tools", mimeType: "application/json" },
    "POST /api/website-contacts": { accepts: p("$0.180000"), description: "Website Contacts - Tools", mimeType: "application/json" },
    "POST /api/website-contacts-scraper": { accepts: p("$0.160000"), description: "Website Contacts Scraper - Tools", mimeType: "application/json" },
    "POST /api/website-intelligence": { accepts: p("$0.150000"), description: "Website Intelligence - Tools", mimeType: "application/json" },
    "POST /api/website-screenshot": { accepts: p("$0.180000"), description: "Website Screenshot - Tools", mimeType: "application/json" },
    "POST /api/website-social": { accepts: p("$0.080000"), description: "Website Social - Tools", mimeType: "application/json" },
    "POST /api/website-social-scraper": { accepts: p("$0.170000"), description: "Website Social Scraper - Tools", mimeType: "application/json" },
    "POST /api/website-social-scraper-api": { accepts: p("$0.110000"), description: "Website Social Scraper Api - Tools", mimeType: "application/json" },
    "POST /api/whatsapp-data": { accepts: p("$0.130000"), description: "Whatsapp Data - Social Media", mimeType: "application/json" },
    "POST /api/whatsapp-validator": { accepts: p("$0.060000"), description: "Whatsapp Validator - Social Media", mimeType: "application/json" },
    "POST /api/whatsapp-validator3": { accepts: p("$0.180000"), description: "Whatsapp Validator3 - Social Media", mimeType: "application/json" },
    "POST /api/workday-jobs-api": { accepts: p("$0.050000"), description: "Workday Jobs Api - Other", mimeType: "application/json" },
    "POST /api/x-checker": { accepts: p("$0.110000"), description: "X Checker - Social Media", mimeType: "application/json" },
    "POST /api/x-com2": { accepts: p("$0.160000"), description: "X Com2 - Social Media", mimeType: "application/json" },
    "POST /api/x-search": { accepts: p("$0.180000"), description: "X Search - Social Media", mimeType: "application/json" },
    "POST /api/x-twitter-api": { accepts: p("$0.070000"), description: "X Twitter Api - Social Media", mimeType: "application/json" },
    "POST /api/x-twitter-user": { accepts: p("$0.150000"), description: "X Twitter User - Social Media", mimeType: "application/json" },
    "POST /api/xai": { accepts: p("$0.150000"), description: "Xai - AI", mimeType: "application/json" },
    "POST /api/yahoo-finance127": { accepts: p("$0.080000"), description: "Yahoo Finance127 - Finance", mimeType: "application/json" },
    "POST /api/yahoo-weather": { accepts: p("$0.140000"), description: "Yahoo Weather - Weather", mimeType: "application/json" },
    "POST /api/yahoo-weather5": { accepts: p("$0.140000"), description: "Yahoo Weather5 - Weather", mimeType: "application/json" },
    "POST /api/yield/best-pools": { accepts: p("$0.180000"), description: "Yield Best Pools - Other", mimeType: "application/json" },
    "POST /api/yield/lending": { accepts: p("$0.150000"), description: "Yield Lending - Other", mimeType: "application/json" },
    "POST /api/yield/stablecoin": { accepts: p("$0.170000"), description: "Yield Stablecoin - Crypto", mimeType: "application/json" },
    "POST /api/yield/strategy": { accepts: p("$0.140000"), description: "Yield Strategy - Other", mimeType: "application/json" },
    "POST /api/ylytic-influencers": { accepts: p("$0.090000"), description: "Ylytic Influencers - Other", mimeType: "application/json" },
    "POST /api/youtube-dl": { accepts: p("$0.110000"), description: "Youtube Dl - Social Media", mimeType: "application/json" },
    "POST /api/youtube-media-downloader": { accepts: p("$0.180000"), description: "Youtube Media Downloader - Social Media", mimeType: "application/json" },
    "POST /api/youtube-mp3": { accepts: p("$0.170000"), description: "Youtube Mp3 - Social Media", mimeType: "application/json" },
    "POST /api/youtube-mp3-audio": { accepts: p("$0.100000"), description: "Youtube Mp3 Audio - Social Media", mimeType: "application/json" },
    "POST /api/youtube-mp4": { accepts: p("$0.140000"), description: "Youtube Mp4 - Social Media", mimeType: "application/json" },
    "POST /api/youtube-search": { accepts: p("$0.170000"), description: "Youtube Search - Social Media", mimeType: "application/json" },
    "POST /api/youtube-telegram-upload": { accepts: p("$0.050000"), description: "Youtube Telegram Upload - Social Media", mimeType: "application/json" },
    "POST /api/youtube-v2": { accepts: p("$0.140000"), description: "Youtube V2 - Social Media", mimeType: "application/json" },
    "POST /api/youtube138": { accepts: p("$0.140000"), description: "Youtube138 - Social Media", mimeType: "application/json" },
    "POST /api/yt-api": { accepts: p("$0.110000"), description: "Yt Api - Social Media", mimeType: "application/json" },
    "GET /api/defillama-protocols": { accepts: p("$0.020000"), description: "DeFiLlama Protocol List", mimeType: "application/json" },
    "GET /api/defillama-tvl": { accepts: p("$0.020000"), description: "DeFiLlama TVL Rankings", mimeType: "application/json" },
    "GET /api/defillama-yields": { accepts: p("$0.030000"), description: "DeFiLlama Yield Opportunities", mimeType: "application/json" },
    "GET /api/dexscreener-trending": { accepts: p("$0.020000"), description: "DexScreener Trending Tokens", mimeType: "application/json" },
    "GET /api/dexscreener-new-pairs": { accepts: p("$0.030000"), description: "DexScreener New DEX Pairs", mimeType: "application/json" },
    "GET /api/coingecko-market": { accepts: p("$0.030000"), description: "CoinGecko Market Data", mimeType: "application/json" },
    "GET /api/coingecko-coin": { accepts: p("$0.040000"), description: "CoinGecko Coin Details", mimeType: "application/json" },
    "GET /api/coingecko-trending": { accepts: p("$0.020000"), description: "CoinGecko Trending", mimeType: "application/json" },
    "GET /api/fear-greed": { accepts: p("$0.010000"), description: "Crypto Fear & Greed Index", mimeType: "application/json" }
  },
  server,
);

export const config = { matcher: ["/api/:path*"] };
